# Site settings
title: Rizky Saskia Putra
subtitle: "This is cdn"
copyright_name: Rizky Saskia Putra
description: "This is blog."
url: "https://rizkysaskiaputra.github.io"
author: Rizky Saskia Putra
github_username:  rizkysaskiaputra
email_username:  fromdeveloper@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
