# Site settings
title: Rizky Saskia Putra
subtitle: "This is cdn"
copyright_name: Rizky Saskia Putra
author: Rizky Saskia Putra
github_username:  rizkysaskiaputra
email_username:  fromdeveloper@gmail.com
google_site_verification: xYKteXWFFpnt9Sdqy_0ZtiyhFtafYSNNQr5xfHgN59o

# Build settings
markdown: kramdown
auto_ids: false
highlighter: rouge
paginate: 5

gems: [jekyll-paginate, jekyll-feed, jekyll-sitemap]
